name: ML Pipeline Trigger

on:
  push:
    branches:
      - main  # main 브랜치에 push가 발생할 때 작업을 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 가장 최신의 Ubuntu 환경에서 실행

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 코드 체크아웃

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 파이썬 버전 설정

    - name: Install dependencies
      run: |
        pip install nbformat  # 필요한 패키지 설치
        pip install google-cloud-aiplatform  # Google Cloud API 사용을 위한 패키지 설치

    - name: Execute Jupyter notebook
      run: |
        # Jupyter notebook 실행을 위한 커맨드, 이는 실제 실행 방법에 따라 다를 수 있음
        jupyter nbconvert --to notebook --execute your-notebook.ipynb --output executed_notebook.ipynb
